---
- name: deploy web
  hosts: web

  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: latest

  - name: website
    shell: echo "hello vagrant" > /usr/share/nginx/html/index.html

  - name: health endpoint
    shell: echo "OK" > /usr/share/nginx/html/health.html

  - name: start nginx
    systemd:
      name: nginx
      state: started
      enabled: yes



- name: deploy haproxy
  hosts: haproxy

  tasks:
  - name: rt_tables entry
    lineinfile:
      path: /etc/iproute2/rt_tables
      line: "200 public"

  - name: ip route
    shell: >
        ip route flush table public
        ; ip rule delete table public 
        ; ip rule add dev eth1 table public priority 1
        && ip route add default via {{ gw }} dev eth1 table public

  - name: install haproxy
    yum:
      name: haproxy
      state: latest
      
  - name: haproxy config
    template:
      src: haproxy.j2
      dest: /etc/haproxy/haproxy.cfg
      
  - name: sysctl nonlocal_bind=1
    sysctl:
      name: net.ipv4.ip_nonlocal_bind
      value: "1"
      sysctl_set: yes
      state: present
      reload: yes
      
  - name: start haproxy
    systemd:
      name: haproxy
      state: restarted
      enabled: yes
      
  - name: install keepalived
    yum:
      name: keepalived
      state: latest
      
  - name: keepalived config
    template:
      src: keepalived.j2
      dest: /etc/keepalived/keepalived.conf
      
  - name: start keepalived
    systemd:
      name: keepalived
      state: restarted
      enabled: yes  

