---
- name: deploy web
  hosts: web

  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: latest

  - name: website
    shell: echo "hello vagrant" > /usr/share/nginx/html/index.html

  - name: health endpoint
    shell: echo "OK" > /usr/share/nginx/html/health.html

  - name: start nginx
    systemd:
      name: nginx
      state: started
      enabled: yes

- name: deploy haproxy
  hosts: haproxy

  tasks:
  - name: install haproxy
    yum:
      name: haproxy
      state: latest
  - name: haproxy config
    template:
      src: haproxy.j2
      dest: /etc/haproxy/haproxy.cfg
  - name: start haproxy
    systemd:
      name: haproxy
      state: started
      enabled: yes  
  - name: install keepalived
    yum:
      name: keepalived
      state: latest
#configure keepalived
  - name: start keepalived
    systemd:
      name: keepalived
      state: started
      enabled: yes  

